---
driver_plugin: openstack

platforms:
- name: ubuntu-12.04
  driver_config:
    openstack_username: <%= ENV['OS_USERNAME'] %>
    openstack_api_key:  <%= ENV['OS_PASSWORD'] %>
    openstack_auth_url:  <%= "#{ENV['OS_AUTH_URL']}/tokens" %>
    image_ref: <%= ENV['UBUNTU_1204'] %> 
    flavor_ref: 1
    key_name: jenkins 
    public_key_path: <%= ENV['SSH_KEY_FILE'] %>
    disable_ssl_verification: true
    openstack_tenant: <%= ENV['OS_TENANT'] %>
    username: ubuntu
    run_list:
    - recipe[apt]
- name: centos-6.4
  driver_config:
    openstack_username: <%= ENV['OS_USERNAME'] %>
    openstack_api_key:  <%= ENV['OS_PASSWORD'] %>
    openstack_auth_url:  <%= "#{ENV['OS_AUTH_URL']}/tokens" %>
    image_ref: <%= ENV['CENTOS_64'] %>
    flavor_ref: 1
    key_name: jenkins
    public_key_path: <%= ENV['SSH_KEY_FILE'] %>
    disable_ssl_verification: true
    openstack_tenant: <%= ENV['OS_TENANT'] %>
    username: stack
