driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[rackspace_apt::default]
  - name: debian-7.2
    run_list:
      - recipe[rackspace_apt::default]
  - name: centos-6.4
    run_list:
      - recipe[rackspace_yum::default]

suites:
  - name: client
    run_list:
      - recipe[mysql_test::client]
  - name: ruby
    run_list:
      - recipe[rackspace_mysql::ruby]
  - name: server
    run_list:
      - recipe[mysql_test::server]
  - name: server-nondefault-data
    run_list:
      - recipe[mysql_test::server]
    attributes:
      mysql:
        data_dir: "/data/mysql"
